<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Shorts_ui-menu-icon ui-icon ui-icon-carat-1-e</name>
   <tag></tag>
   <elementGuidId>fcec6310-69e8-4299-aa45-35549d55102d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ui-id-6 > span.ui-menu-icon.ui-icon.ui-icon-carat-1-e</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-6']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c53764dc-d546-4d51-a6e9-8164192a8f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menu-icon ui-icon ui-icon-carat-1-e</value>
      <webElementGuid>ea08e36c-c927-4d62-a42c-1c317edfac51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-6&quot;)/span[@class=&quot;ui-menu-icon ui-icon ui-icon-carat-1-e&quot;]</value>
      <webElementGuid>680665e2-5ffc-4f3a-b984-c76dad195eb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ui-id-6']/span</value>
      <webElementGuid>ac3e2525-8b8e-4ffb-ac43-f8ca1e2a49c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span</value>
      <webElementGuid>a9592c67-8052-4a41-9ffd-43df598a6110</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
